name: Default Issue Closed Handling

on:
  issues:
    types:
      - closed

jobs:
  remove-labels-when-closed:
    runs-on: [self-hosted, nano]
    timeout-minutes: 3
    steps:
      - name: Remove all specified labels if present
        uses: peter-murray/remove-labels-action@v1
        with:
          labels: in progress
