name: Default Issue Labeled Handling

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  in-progress-check:
    runs-on: [self-hosted, nano]
    timeout-minutes: 3
    if: github.event.action == 'labeled' && github.event.label.name == 'in progress'
    steps:
      - name: Call API for In Progress
        uses: dkershner6/post-api-call-action@v1
        with:
          url: 'https://${{ secrets.DEVOPS_API_DOMAIN }}/github/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/in_progress'
          headers: '{"Authorization": "Bearer ${{ secrets.DEVOPS_API_KEY }}"}'

  in-progress-label-update:
    runs-on: [self-hosted, nano]
    timeout-minutes: 3
    if: github.event.action != 'labeled' || github.event.label.name != 'in progress'
    steps:
      - name: Call API for In Progress Labels
        uses: dkershner6/post-api-call-action@v1
        with:
          url: 'https://${{ secrets.DEVOPS_API_DOMAIN }}/github/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/in_progress_labels'
          headers: '{"Authorization": "Bearer ${{ secrets.DEVOPS_API_KEY }}"}'
