name: Manual - Implement Repo Settings

on: workflow_dispatch

jobs:
  implement-default-settings:
    runs-on: [self-hosted, nano]
    timeout-minutes: 3
    steps:
      - name: Call API for Implementing Default Settings
        uses: dkershner6/post-api-call-action@v1
        with:
          url: 'https://api.devops.eformedpartners.com/github/repos/${{ github.repository }}/default_settings'
          headers: '{"Authorization": "Bearer ${{ secrets.DEVOPS_API_KEY }}"}'
